### ISSUE TITLE
RFE: exclude PRs that are drafts

### ISSUE THREAD

**Issue by knabar** [ome/scc#262]
GitHub introduced draft PRs a while ago:
https://github.blog/2019-02-14-introducing-draft-pull-requests/

It would be great if draft mode worked like `--exclude`!

**Comment by sbesson** [comment]
Thanks. The draft attribute has been introduced ~1 year ago recent versions of PyGithub have support for it with a [boolean attribute](https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.draft) allowing to introspect its value.

I expect a combination of enforcing a minimum version of `PyGithub` in `setup.py` + updating https://github.com/ome/scc/blob/master/scc/git.py#L900 to test this attribute should be a good starting point.

Main question in terms of API would be:

- how to allow the user to control the inclusion/exclusion draft PRs via the API/command options e.g. what should be passed to `--include/exclude`?
- what should be the default behavior? I also agree excluding draft PRs by default would make sense so that would be a breaking version increment.

**Comment by melissalinkert** [comment]
I was surprised by this in https://github.com/ome/bioformats/pull/3883#issuecomment-1268429792, so another :+1: for excluding drafts by default.

**Comment by sbesson** [comment]
Thanks @melissalinkert for raising this issue again. This is timely as it follows a decision from the @ome/formats team to make better usage of draft PRs to communicate the in-progress PRs and clarify expectations in terms of review.

In terms of CI, I would also concur that the "not yet ready for review" nature of these PRs (see the original [announcement](https://github.blog/2019-02-14-introducing-draft-pull-requests/)) supports the idea of not including them in the default integration builds.

Before starting to look into the implementation, based on the ownership of the [current set of open draft PRs](https://github.com/pulls?page=1&q=is%3Aopen+is%3Apr+org%3Aome+org%3AIDR+draft%3Atrue), @dgault @dominikl @will-moore would you have any objection with this change of semantics?

/cc @joshmoore @jburel

**Comment by will-moore** [comment]
Makes sense 👍

**Comment by sbesson** [comment]
Now released as https://pypi.org/project/scc/0.19.0/. This should start appearing in the builds over the next few days
